# We intentionally ignore some suggestions.
# For some reason `weeder` thinks that `base-noprelude` is useless
# while it is not.
- package:
  - name: morley
  - section:
    - name: exe:morley
    - message:
      - name: Redundant build-depends entry
      - depends: base-noprelude
  - section:
    - name: exe:contract-discover
    - message:
      - name: Redundant build-depends entry
      - depends: base-noprelude
  - section:
    - name: library
    - message:
      - name: Redundant build-depends entry
      - depends:
        - base-noprelude
        # We don't use transformers-compat directly,
        # but we have to specify its version explicitly in .cabal file
        # because otherwise Hackage build fails.
        - transformers-compat
  - section:
    - name: test:morley-test
    - message:
      - name: Redundant build-depends entry
      - depends: base-noprelude
  - section:
    - name: test:morley-test
    - message:
      - name: Weeds exported
      - identifier:
        - ingredients
        - main

- package:
  - name: morley-prelude
  - section:
    - name: library
    - message:
      - name: Redundant build-depends entry
      - depends:
        - base-noprelude

- package:
  - name: lorentz-contracts
  - section:
    - name: library
    - message:
      - name: Redundant build-depends entry
      - depends:
        - morley-prelude  # Needed for autogenerated modules
        - base-noprelude
    - message:  # TODO [TM-158] Revert
      - name: Excessive other-modules entry
      - module:
        - Test.Lorentz.Contracts.Registry
        - Test.Lorentz.Contracts.Registry.Types
        - Test.Lorentz.Contracts.Registry.Impl
    - message:  # TODO [TM-158] Revert
      - name: Weeds exported
      - identifier:
        - AddWallet
        - GetAttribute
        - GetCountry
        - GetInvestor
        - InvestorExists
        - Parameter
        - RegisterInvestor
        - RemoveInvestor
        - RemoveWallet
        - SetCountry
        - Storage
        - WalletExists
        - registryContract
  - section:
    - name: exe:lorentz-contracts
    - message:
      - name: Redundant build-depends entry
      - depends: base-noprelude
  - section:
    - name: test:lorentz-contracts-test
    - message:
      - name: Redundant build-depends entry
      - depends:
        - base-noprelude
  - section:
    - name: test:lorentz-contracts-test
    - message:
      - name: Weeds exported
      - identifier:
        - ingredients
        - main
