<<: !include "./hpack/module.yaml"

<<: *meta
name:                lorentz-contract-param
version:             1.2.0.1.3
synopsis:            Set of Michelson contracts implemented in Lorentz eDSL, with CLI interface
description:
  Various contracts including simple examples.
category:            Language
extra-source-files:
  - README.md

library:
  <<: *lorentz-lib-common

  dependencies:
    - containers
    - data-default
    - fmt
    - morley
    - morley-prelude
    - named
    - singletons
    - text
    - vinyl
    - cryptonite
    - bytestring
    - aeson
    - constraints
    - binary
    - lorentz-contracts

executables:
  lorentz-contract:
    <<: *exec-common

    dependencies:
      - containers
      - fmt
      - lorentz-contracts
      - morley
      - morley-prelude
      - optparse-applicative
      - singletons
      - text
      - megaparsec
      - lorentz-contract-param

  lorentz-contract-param:
    <<: *exec-common

    main: Main.hs
    source-dirs: param-app

    dependencies:
      - containers
      - fmt
      - lorentz-contracts
      - morley
      - morley-prelude
      - optparse-applicative
      - text
      - named
      - singletons
      - binary
      - bytestring
      - constraints
      - aeson
      - aeson-pretty
      - lorentz-contract-param

  lorentz-contract-storage:
    <<: *exec-common

    main: Main.hs
    source-dirs: storage-app

    dependencies:
      - containers
      - fmt
      - lorentz-contracts
      - morley
      - morley-prelude
      - optparse-applicative
      - text
      - named
      - singletons
      - lorentz-contract-param

tests:
  lorentz-contract-param-test:
    <<: *test-common

    dependencies:
      - containers
      - data-default
      - fmt
      - hspec
      - hspec-expectations
      - HUnit
      - lorentz-contracts
      - morley
      - morley-prelude
      - QuickCheck
      - singletons
      - tasty
      - tasty-hspec
      - tasty-hunit
      - tasty-quickcheck
      - vinyl
      - lorentz-contract-param
      - quickcheck-instances
      - named
      - cryptonite
      - aeson
      - text
      - memory

