<<: !include "./hpack/module.yaml"

<<: *meta
name:                lorentz-contracts
version:             0.2.0.1
synopsis:            Set of Michelson contracts implemented in Lorentz eDSL.
description:
  Various contracts including simple examples.
category:            Language
extra-source-files:
  - README.md

library:
  <<: *lorentz-lib-common

  dependencies:
    - containers
    - data-default
    - fmt
    - morley
    - morley-prelude
    - text
    - vinyl

executables:
  lorentz-contracts:
    <<: *exec-common

    dependencies:
      - containers
      - fmt
      - lorentz-contracts
      - morley
      - morley-prelude
      - optparse-applicative
      - text

  lorentz-contract-param:
    <<: *exec-common

    main: Main.hs
    source-dirs: param-app

    dependencies:
      - containers
      - fmt
      - lorentz-contracts
      - morley
      - morley-prelude
      - optparse-applicative
      - text
      - named
      - singletons

tests:
  lorentz-contracts-test:
    <<: *test-common

    dependencies:
      - containers
      - data-default
      - fmt
      - hspec
      - hspec-expectations
      - HUnit
      - lorentz-contracts
      - morley
      - morley-prelude
      - QuickCheck
      - singletons
      - tasty
      - tasty-hspec
      - tasty-hunit
      - tasty-quickcheck
      - vinyl
